package co.edu.uniquindio.compilers.lexicalAnalyzer

enum class Category {
    ENTERO,
    DECIMAL,
    IDENTIFICADOR,
    OPERADOR_ARITMETICO,
    OPERADOR_INCREMENTO,
    OPERADOR_DECREMENTO,
    OPERADOR_LOGICO,
    PARENTESIS_IZQUIERDO,
    PARENTESIS_DERECHO,
    CORCHETES,
    OPERADORES_RELACIONALES,
    DESCONOCIDO,
    CADENA_CARACTERES
}